export const GLOSSARY_TOPICS = ["All topics", "AI operations", "Reliability", "Telemetry", "Delivery"] as const;
export type GlossaryTopic = Exclude<(typeof GLOSSARY_TOPICS)[number], "All topics">;
export interface GlossaryTerm {
  slug: string; name: string; aliases: string[]; topic: GlossaryTopic;
  definition: string; why: string; source: { title: string; url: string };
  related: string[]; catalog: { label: string; href: string };
}
const sources = {
  intro: { title: "Google SRE: Introduction", url: "https://sre.google/sre-book/introduction/" },
  slo: { title: "Google SRE: Service Level Objectives", url: "https://sre.google/sre-book/service-level-objectives/" },
  toil: { title: "Google SRE: Eliminating Toil", url: "https://sre.google/sre-book/eliminating-toil/" },
  monitoring: { title: "Google SRE: Monitoring Distributed Systems", url: "https://sre.google/sre-book/monitoring-distributed-systems/" },
  signals: { title: "OpenTelemetry: Signals", url: "https://opentelemetry.io/docs/concepts/signals/" },
  agents: { title: "Anthropic: Building effective agents", url: "https://www.anthropic.com/engineering/building-effective-agents" },
  gitops: { title: "OpenGitOps: Principles", url: "https://opengitops.dev/" },
  postmortem: { title: "Google SRE: Postmortem Culture", url: "https://sre.google/sre-book/postmortem-culture/" },
};
const tools = { label: "Explore AI SRE tools", href: "/tools" };
const telemetry = { label: "Explore observability tools", href: "/observability" };
const pilot = { label: "Use the pilot scorecard", href: "/resources/ai-sre-pilot-scorecard" };
export const GLOSSARY_CHECKED_AT = "2026-09-30";
export const GLOSSARY_TERMS: GlossaryTerm[] = ([
  { slug: "ai-sre", name: "AI SRE", aliases: ["AI site reliability engineering"], topic: "AI operations", definition: "A working category for AI-assisted reliability operations, such as incident investigation or response. It is not a standardized capability level: an assistant, workflow, and autonomous agent can have very different authority.", why: "Evaluate the specific tasks and permissions rather than the product label.", source: sources.agents, related: ["agent", "workflow", "sre"], catalog: { label: "Read the OpenObserve Enterprise preview", href: "/tools/openobserve-ai-sre" } },
  { slug: "agent", name: "Agent", aliases: ["AI agent", "LLM agent"], topic: "AI operations", definition: "An AI system in which a model chooses its next steps and tool use dynamically, rather than following only predefined execution paths.", why: "Check which actions it can take and when a person must approve them.", source: sources.agents, related: ["workflow", "ai-sre"], catalog: pilot },
  { slug: "workflow", name: "Workflow", aliases: ["AI workflow", "automation"], topic: "AI operations", definition: "A system that coordinates model calls and tools through predefined code paths. Model use alone does not make a workflow an autonomous agent.", why: "Predictable steps and action boundaries can make a narrow task easier to evaluate.", source: sources.agents, related: ["agent", "gitops"], catalog: tools },
  { slug: "sre", name: "Site reliability engineering", aliases: ["SRE"], topic: "Reliability", definition: "Applying software engineering to operating services, with reliability goals, automation, and engineering work that reduces recurring operational effort.", why: "Judge an improvement by service reliability and durable reduction of work.", source: sources.intro, related: ["toil", "slo", "devops"], catalog: pilot },
  { slug: "devops", name: "DevOps", aliases: ["development and operations"], topic: "Delivery", definition: "Practices that connect development and operations throughout a system's lifecycle, emphasizing collaboration, automation, and engineering approaches to operational work.", why: "It describes how teams work together, not a particular tool or job title.", source: sources.intro, related: ["sre", "gitops", "workflow"], catalog: tools },
  { slug: "sli", name: "Service level indicator", aliases: ["SLI"], topic: "Reliability", definition: "A defined measurement of service behavior, such as the proportion of successful requests or request latency.", why: "Choose measurements that represent what users actually experience.", source: sources.slo, related: ["slo", "latency"], catalog: pilot },
  { slug: "slo", name: "Service level objective", aliases: ["SLO"], topic: "Reliability", definition: "A target for a service level indicator. State the measurement, acceptable threshold, and evaluation window so success can be assessed consistently.", why: "An explicit target lets a team discuss reliability tradeoffs.", source: sources.slo, related: ["sli", "sla", "error-budget"], catalog: pilot },
  { slug: "sla", name: "Service level agreement", aliases: ["SLA"], topic: "Reliability", definition: "An agreement about service levels with consequences when those levels are missed. An internal reliability target alone is not an SLA.", why: "Separate contractual commitments from engineering targets.", source: sources.slo, related: ["slo", "sli"], catalog: pilot },
  { slug: "error-budget", name: "Error budget", aliases: [], topic: "Reliability", definition: "The amount of unreliability permitted by a service level objective over its measurement window.", why: "Track consumption to inform the balance between change and reliability work.", source: sources.slo, related: ["slo", "sli"], catalog: pilot },
  { slug: "toil", name: "Toil", aliases: ["operational toil"], topic: "Reliability", definition: "Recurring service-operation work that is manual, repetitive, automatable, and produces little lasting improvement. It often grows as the service grows.", why: "Measure work eliminated, including the effort needed to supervise automation.", source: sources.toil, related: ["sre", "workflow"], catalog: tools },
  { slug: "latency", name: "Latency", aliases: ["response time"], topic: "Telemetry", definition: "The time a request takes to complete. Successful and failed requests may need separate measurements; an average can hide slow requests.", why: "Use the distribution and user-facing thresholds when assessing service performance.", source: sources.monitoring, related: ["sli", "metrics", "traces"], catalog: telemetry },
  { slug: "golden-signals", name: "Golden signals", aliases: ["four golden signals"], topic: "Telemetry", definition: "Four monitoring dimensions emphasized by Google SRE: latency, traffic, errors, and saturation.", why: "They provide a starting point for detecting symptoms of service trouble.", source: sources.monitoring, related: ["latency", "metrics", "sli"], catalog: telemetry },
  { slug: "black-box-monitoring", name: "Black-box monitoring", aliases: ["synthetic monitoring"], topic: "Telemetry", definition: "Observing externally visible behavior as a user would experience it. Synthetic checks are one way to perform these observations.", why: "Compare user-visible failure with internal telemetry during an investigation.", source: sources.monitoring, related: ["golden-signals", "sli"], catalog: telemetry },
  { slug: "logs", name: "Logs", aliases: ["log records"], topic: "Telemetry", definition: "Records of events emitted by a system. Structured fields and timestamps help connect an event to its execution context.", why: "A record is useful evidence, but its presence alone does not establish causality.", source: sources.signals, related: ["metrics", "traces", "root-cause-analysis"], catalog: telemetry },
  { slug: "metrics", name: "Metrics", aliases: ["time series"], topic: "Telemetry", definition: "Measurements captured over time, such as request counts or resource utilization. Aggregation helps describe system behavior across many events.", why: "Use labels, units, and time windows consistently when comparing signals.", source: sources.signals, related: ["logs", "traces", "sli"], catalog: telemetry },
  { slug: "traces", name: "Traces", aliases: ["distributed tracing", "spans"], topic: "Telemetry", definition: "Records of a request's path through a system. A trace contains spans representing operations and their relationships.", why: "Follow dependencies and timing instead of treating each service in isolation.", source: sources.signals, related: ["logs", "metrics", "latency"], catalog: telemetry },
  { slug: "gitops", name: "GitOps", aliases: [], topic: "Delivery", definition: "Operating a system from declarative desired state that is versioned and immutable, pulled automatically, and continuously reconciled by software agents.", why: "A Git repository alone is not enough; reconciliation connects desired and actual state.", source: sources.gitops, related: ["devops", "workflow"], catalog: tools },
  { slug: "postmortem", name: "Postmortem", aliases: ["incident review", "blameless postmortem"], topic: "Reliability", definition: "A written incident review covering impact, response, contributing causes, and follow-up actions. A blameless review investigates the system and context rather than assigning personal fault.", why: "Turn an incident into specific reliability improvements with owners.", source: sources.postmortem, related: ["root-cause-analysis", "sre", "toil"], catalog: { label: "Explore incident workflow stages", href: "/resources/ai-sre-incident-workflow-map" } },
  { slug: "root-cause-analysis", name: "Root cause analysis", aliases: ["RCA"], topic: "Reliability", definition: "Investigating the causes and contributing conditions of an incident. A plausible explanation is a hypothesis until it is supported by evidence.", why: "Keep observed facts, interpretations, and proposed fixes separate.", source: sources.postmortem, related: ["postmortem", "logs", "traces"], catalog: tools },
] satisfies GlossaryTerm[]).sort((a, b) => a.name.localeCompare(b.name));
export function filterGlossary(query: string, topic: string) {
  const needle = query.trim().toLocaleLowerCase();
  const candidates = GLOSSARY_TERMS.filter(term => topic === "All topics" || term.topic === topic);
  const exact = GLOSSARY_TERMS.filter(term => [term.name, ...term.aliases].some(text => text.toLocaleLowerCase() === needle));
  if (exact.length) return exact.filter(term => topic === "All topics" || term.topic === topic);
  return candidates.filter(term => [term.name, ...term.aliases, term.definition].some(text => text.toLocaleLowerCase().includes(needle)));
}
